
def build(bld):

    if bld.env['HAS_C++11']:

        bld.program(
            target = 'tpc-readraw-timing',
            source = ['tpc-readraw-timing.cpp'],
            includes = ['#src'],
            use = '''\
                C++11
                BOOST
                    boost_filesystem
            ''')
