//
// File generated by rootcint at Thu Feb 19 14:48:34 2015

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME main_window_dict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "main_window_dict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void MainWindow_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void delete_MainWindow(void *p);
   static void deleteArray_MainWindow(void *p);
   static void destruct_MainWindow(void *p);
   static void streamer_MainWindow(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::MainWindow*)
   {
      ::MainWindow *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::MainWindow >(0);
      static ::ROOT::TGenericClassInfo 
         instance("MainWindow", ::MainWindow::Class_Version(), "./main_window.hpp", 5,
                  typeid(::MainWindow), ::ROOT::DefineBehavior(ptr, ptr),
                  &::MainWindow::Dictionary, isa_proxy, 0,
                  sizeof(::MainWindow) );
      instance.SetDelete(&delete_MainWindow);
      instance.SetDeleteArray(&deleteArray_MainWindow);
      instance.SetDestructor(&destruct_MainWindow);
      instance.SetStreamerFunc(&streamer_MainWindow);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::MainWindow*)
   {
      return GenerateInitInstanceLocal((::MainWindow*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::MainWindow*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

//______________________________________________________________________________
atomic_TClass_ptr MainWindow::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *MainWindow::Class_Name()
{
   return "MainWindow";
}

//______________________________________________________________________________
const char *MainWindow::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::MainWindow*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int MainWindow::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::MainWindow*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void MainWindow::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::MainWindow*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *MainWindow::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::MainWindow*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void MainWindow::Streamer(TBuffer &R__b)
{
   // Stream an object of class MainWindow.

   TGMainFrame::Streamer(R__b);
}

//______________________________________________________________________________
void MainWindow::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class MainWindow.
      TClass *R__cl = ::MainWindow::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fEcanvas", &fEcanvas);
      R__insp.InspectMember(fEcanvas, "fEcanvas.");
      TGMainFrame::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrapper around operator delete
   static void delete_MainWindow(void *p) {
      delete ((::MainWindow*)p);
   }
   static void deleteArray_MainWindow(void *p) {
      delete [] ((::MainWindow*)p);
   }
   static void destruct_MainWindow(void *p) {
      typedef ::MainWindow current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_MainWindow(TBuffer &buf, void *obj) {
      ((::MainWindow*)obj)->::MainWindow::Streamer(buf);
   }
} // end of namespace ROOTDict for class ::MainWindow

/********************************************************
* main_window_dict.cpp
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtablemain_window_dict();

extern "C" void G__set_cpp_environmentmain_window_dict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("main_window.hpp");
  G__cpp_reset_tagtablemain_window_dict();
}
#include <new>
extern "C" int G__cpp_dllrevmain_window_dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* MainWindow */
static int G__main_window_dict_315_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   MainWindow* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 3
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new MainWindow(
(TGWindow*) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]));
   } else {
     p = new((void*) gvp) MainWindow(
(TGWindow*) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__main_window_dictLN_MainWindow));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__main_window_dict_315_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MainWindow*) G__getstructoffset())->DoDraw();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__main_window_dict_315_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) MainWindow::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__main_window_dict_315_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) MainWindow::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__main_window_dict_315_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) MainWindow::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__main_window_dict_315_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      MainWindow::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__main_window_dict_315_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MainWindow*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__main_window_dict_315_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) MainWindow::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__main_window_dict_315_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) MainWindow::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__main_window_dict_315_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) MainWindow::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__main_window_dict_315_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) MainWindow::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef MainWindow G__TMainWindow;
static int G__main_window_dict_315_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (MainWindow*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((MainWindow*) (soff+(sizeof(MainWindow)*i)))->~G__TMainWindow();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (MainWindow*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((MainWindow*) (soff))->~G__TMainWindow();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* MainWindow */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncmain_window_dict {
 public:
  G__Sizep2memfuncmain_window_dict(): p(&G__Sizep2memfuncmain_window_dict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncmain_window_dict::*p)();
};

size_t G__get_sizep2memfuncmain_window_dict()
{
  G__Sizep2memfuncmain_window_dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancemain_window_dict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__main_window_dictLN_MainWindow))) {
     MainWindow *G__Lderived;
     G__Lderived=(MainWindow*)0x1000;
     {
       TGMainFrame *G__Lpbase=(TGMainFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__main_window_dictLN_MainWindow),G__get_linked_tagnum(&G__main_window_dictLN_TGMainFrame),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TGCompositeFrame *G__Lpbase=(TGCompositeFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__main_window_dictLN_MainWindow),G__get_linked_tagnum(&G__main_window_dictLN_TGCompositeFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGFrame *G__Lpbase=(TGFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__main_window_dictLN_MainWindow),G__get_linked_tagnum(&G__main_window_dictLN_TGFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGWindow *G__Lpbase=(TGWindow*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__main_window_dictLN_MainWindow),G__get_linked_tagnum(&G__main_window_dictLN_TGWindow),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGObject *G__Lpbase=(TGObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__main_window_dictLN_MainWindow),G__get_linked_tagnum(&G__main_window_dictLN_TGObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__main_window_dictLN_MainWindow),G__get_linked_tagnum(&G__main_window_dictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TQObject *G__Lpbase=(TQObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__main_window_dictLN_MainWindow),G__get_linked_tagnum(&G__main_window_dictLN_TQObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablemain_window_dict() {

   /* Setting up typedef entry */
   G__search_typename2("UInt_t",104,-1,0,-1);
   G__setnewtype(-1,"Unsigned integer 4 bytes (unsigned int)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__main_window_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__main_window_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__main_window_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__main_window_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__main_window_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__main_window_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__main_window_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__main_window_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__main_window_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__main_window_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<UInt_t,Int_t>",117,G__get_linked_tagnum(&G__main_window_dictLN_pairlEunsignedsPintcOintgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__main_window_dictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__main_window_dictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__main_window_dictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__main_window_dictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__main_window_dictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__main_window_dictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<unsigned int,int> >",117,G__get_linked_tagnum(&G__main_window_dictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__main_window_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__main_window_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__main_window_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__main_window_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__main_window_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* MainWindow */
static void G__setup_memvarMainWindow(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__main_window_dictLN_MainWindow));
   { MainWindow *p; p=(MainWindow*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__main_window_dictLN_TRootEmbeddedCanvas),-1,-1,4,"fEcanvas=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__main_window_dictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarmain_window_dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncMainWindow(void) {
   /* MainWindow */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__main_window_dictLN_MainWindow));
   G__memfunc_setup("MainWindow",1021,G__main_window_dict_315_0_1, 105, G__get_linked_tagnum(&G__main_window_dictLN_MainWindow), -1, 0, 3, 1, 1, 0, 
"U 'TGWindow' - 10 - p h - 'UInt_t' 0 - w "
"h - 'UInt_t' 0 - h", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoDraw",577,G__main_window_dict_315_0_2, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__main_window_dict_315_0_3, 85, G__get_linked_tagnum(&G__main_window_dictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&MainWindow::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__main_window_dict_315_0_4, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&MainWindow::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__main_window_dict_315_0_5, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&MainWindow::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__main_window_dict_315_0_6, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&MainWindow::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__main_window_dictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__main_window_dict_315_0_10, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__main_window_dict_315_0_11, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&MainWindow::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__main_window_dict_315_0_12, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&MainWindow::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__main_window_dict_315_0_13, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&MainWindow::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__main_window_dict_315_0_14, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&MainWindow::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~MainWindow", 1147, G__main_window_dict_315_0_15, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncmain_window_dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalmain_window_dict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcmain_window_dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__main_window_dictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__main_window_dictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__main_window_dictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__main_window_dictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__main_window_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__main_window_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__main_window_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__main_window_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__main_window_dictLN_TGObject = { "TGObject" , 99 , -1 };
G__linked_taginfo G__main_window_dictLN_TQObject = { "TQObject" , 99 , -1 };
G__linked_taginfo G__main_window_dictLN_TGWindow = { "TGWindow" , 99 , -1 };
G__linked_taginfo G__main_window_dictLN_pairlEunsignedsPintcOintgR = { "pair<unsigned int,int>" , 115 , -1 };
G__linked_taginfo G__main_window_dictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR = { "vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >" , 99 , -1 };
G__linked_taginfo G__main_window_dictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >::iterator>" , 99 , -1 };
G__linked_taginfo G__main_window_dictLN_TGFrame = { "TGFrame" , 99 , -1 };
G__linked_taginfo G__main_window_dictLN_TGCompositeFrame = { "TGCompositeFrame" , 99 , -1 };
G__linked_taginfo G__main_window_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__main_window_dictLN_TGMainFrame = { "TGMainFrame" , 99 , -1 };
G__linked_taginfo G__main_window_dictLN_TRootEmbeddedCanvas = { "TRootEmbeddedCanvas" , 99 , -1 };
G__linked_taginfo G__main_window_dictLN_MainWindow = { "MainWindow" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablemain_window_dict() {
  G__main_window_dictLN_TClass.tagnum = -1 ;
  G__main_window_dictLN_TBuffer.tagnum = -1 ;
  G__main_window_dictLN_TMemberInspector.tagnum = -1 ;
  G__main_window_dictLN_TObject.tagnum = -1 ;
  G__main_window_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__main_window_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__main_window_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__main_window_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__main_window_dictLN_TGObject.tagnum = -1 ;
  G__main_window_dictLN_TQObject.tagnum = -1 ;
  G__main_window_dictLN_TGWindow.tagnum = -1 ;
  G__main_window_dictLN_pairlEunsignedsPintcOintgR.tagnum = -1 ;
  G__main_window_dictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR.tagnum = -1 ;
  G__main_window_dictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__main_window_dictLN_TGFrame.tagnum = -1 ;
  G__main_window_dictLN_TGCompositeFrame.tagnum = -1 ;
  G__main_window_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__main_window_dictLN_TGMainFrame.tagnum = -1 ;
  G__main_window_dictLN_TRootEmbeddedCanvas.tagnum = -1 ;
  G__main_window_dictLN_MainWindow.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablemain_window_dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__main_window_dictLN_TClass);
   G__get_linked_tagnum_fwd(&G__main_window_dictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__main_window_dictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__main_window_dictLN_TObject);
   G__get_linked_tagnum_fwd(&G__main_window_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__main_window_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__main_window_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__main_window_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__main_window_dictLN_TGObject);
   G__get_linked_tagnum_fwd(&G__main_window_dictLN_TQObject);
   G__get_linked_tagnum_fwd(&G__main_window_dictLN_TGWindow);
   G__get_linked_tagnum_fwd(&G__main_window_dictLN_pairlEunsignedsPintcOintgR);
   G__get_linked_tagnum_fwd(&G__main_window_dictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__main_window_dictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__main_window_dictLN_TGFrame);
   G__get_linked_tagnum_fwd(&G__main_window_dictLN_TGCompositeFrame);
   G__get_linked_tagnum_fwd(&G__main_window_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__main_window_dictLN_TGMainFrame);
   G__get_linked_tagnum_fwd(&G__main_window_dictLN_TRootEmbeddedCanvas);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__main_window_dictLN_MainWindow),sizeof(MainWindow),-1,62464,(char*)NULL,G__setup_memvarMainWindow,G__setup_memfuncMainWindow);
}
extern "C" void G__cpp_setupmain_window_dict(void) {
  G__check_setup_version(30051515,"G__cpp_setupmain_window_dict()");
  G__set_cpp_environmentmain_window_dict();
  G__cpp_setup_tagtablemain_window_dict();

  G__cpp_setup_inheritancemain_window_dict();

  G__cpp_setup_typetablemain_window_dict();

  G__cpp_setup_memvarmain_window_dict();

  G__cpp_setup_memfuncmain_window_dict();
  G__cpp_setup_globalmain_window_dict();
  G__cpp_setup_funcmain_window_dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncmain_window_dict();
  return;
}
class G__cpp_setup_initmain_window_dict {
  public:
    G__cpp_setup_initmain_window_dict() { G__add_setup_func("main_window_dict",(G__incsetup)(&G__cpp_setupmain_window_dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initmain_window_dict() { G__remove_setup_func("main_window_dict"); }
};
G__cpp_setup_initmain_window_dict G__cpp_setup_initializermain_window_dict;

