/********************************************************************
* main_window_dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error main_window_dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablemain_window_dict();
extern void G__cpp_setup_inheritancemain_window_dict();
extern void G__cpp_setup_typetablemain_window_dict();
extern void G__cpp_setup_memvarmain_window_dict();
extern void G__cpp_setup_globalmain_window_dict();
extern void G__cpp_setup_memfuncmain_window_dict();
extern void G__cpp_setup_funcmain_window_dict();
extern void G__set_cpp_environmentmain_window_dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "main_window.hpp"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__main_window_dictLN_TClass;
extern G__linked_taginfo G__main_window_dictLN_TBuffer;
extern G__linked_taginfo G__main_window_dictLN_TMemberInspector;
extern G__linked_taginfo G__main_window_dictLN_TObject;
extern G__linked_taginfo G__main_window_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__main_window_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__main_window_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__main_window_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__main_window_dictLN_TGObject;
extern G__linked_taginfo G__main_window_dictLN_TQObject;
extern G__linked_taginfo G__main_window_dictLN_TGWindow;
extern G__linked_taginfo G__main_window_dictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__main_window_dictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__main_window_dictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__main_window_dictLN_TGFrame;
extern G__linked_taginfo G__main_window_dictLN_TGCompositeFrame;
extern G__linked_taginfo G__main_window_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__main_window_dictLN_TGMainFrame;
extern G__linked_taginfo G__main_window_dictLN_TRootEmbeddedCanvas;
extern G__linked_taginfo G__main_window_dictLN_MainWindow;

/* STUB derived class for protected member access */
