
def build(bld):
    bld.root_dict(
        target = ['main_window_dict.cpp','main_window_dict.h'],
        source = ['main_window.hpp', 'main_window_linkdef.hpp'],
    )

    bld.program(
        target = 'tpc-online-monitor',
        source = '''\
            tpc-online-monitor.cpp
            main_window.cpp
            main_window_dict.cpp
        '''.split(),
        includes = ['.'],
        use = '''\
            BOOST
                boost_filesystem
            ROOT
        '''
    )
